flowchart LR
    SOBC["SOBC Strategic Case"] --> Point1["Service Standard Point 1:<br/>Understand user needs"]
    SOBC --> Point4["Point 4: Use agile methods"]
    
    EconomicCase["SOBC Economic Case"] --> Point12["Point 12: Make sure users<br/>succeed first time"]
    
    CommercialCase["SOBC Commercial Case"] --> Point11["Point 11: Choose the<br/>right tools and technology"]
    
    FinancialCase["SOBC Financial Case"] --> Point14["Point 14: Operate a<br/>reliable service"]
