graph TB
    TCOP["Technology Code of Practice<br/>13 Points"]
    
    subgraph "User-Centred (1-2)"
        T1["1. Define user needs"]
        T2["2. Make things accessible"]
    end
    
    subgraph "Open (3-4)"
        T3["3. Be open and use<br/>open source"]
        T4["4. Make use of<br/>open standards"]
    end
    
    subgraph "Cloud & Security (5-7)"
        T5["5. Use cloud first"]
        T6["6. Make things secure"]
        T7["7. Make privacy integral"]
    end
    
    subgraph "Sharing (8-10)"
        T8["8. Share, reuse,<br/>collaborate"]
        T9["9. Integrate and<br/>adapt technology"]
        T10["10. Make better use<br/>of data"]
    end
    
    subgraph "Governance (11-13)"
        T11["11. Define purchasing<br/>strategy"]
        T12["12. Meet Digital Spend<br/>Controls"]
        T13["13. Define responsible<br/>AI use"]
    end
    
    TCOP --> T1
    TCOP --> T2
    TCOP --> T3
    TCOP --> T4
    TCOP --> T5
    TCOP --> T6
    TCOP --> T7
    TCOP --> T8
    TCOP --> T9
    TCOP --> T10
    TCOP --> T11
    TCOP --> T12
    TCOP --> T13
