graph TB
    VERSION_FILE["VERSION<br/>3.1.2"]
    
    PRIN["/arckit.principles<br/>Document Control:<br/>ArcKit Version: 3.1.2"]
    
    STAKE["/arckit.stakeholders<br/>Document Control:<br/>ArcKit Version: 3.1.2"]
    
    RISK["/arckit.risk<br/>Document Control:<br/>ArcKit Version: 3.1.2"]
    
    SOBC["/arckit.sobc<br/>Document Control:<br/>ArcKit Version: 3.1.2"]
    
    PLAN["/arckit.plan<br/>Document Control:<br/>ArcKit Version: 3.1.2"]
    
    VERSION_FILE --> PRIN
    VERSION_FILE --> STAKE
    VERSION_FILE --> RISK
    VERSION_FILE --> SOBC
    VERSION_FILE --> PLAN
