graph LR
    A[principles] --> B[stakeholders]
    B --> C[risk]
    C --> D[sobc]
    D --> E[requirements]
    E --> F[dpia]
    F --> G[gcloud-search]
    G --> H[gcloud-clarify]
    H --> I[evaluate]
    I --> J[hld-review]
    J --> K[tcop]
    K --> L[secure]
    L --> M[service-assessment]
