graph TB
    subgraph "User-Centred Design"
        P1["Point 1<br/>Define user needs"]
        P2["Point 2<br/>Make things accessible"]
    end
    
    subgraph "Technology Standards"
        P3["Point 3<br/>Be open and use open source"]
        P4["Point 4<br/>Make use of open standards"]
        P5["Point 5<br/>Use cloud first"]
    end
    
    subgraph "Security & Privacy"
        P6["Point 6<br/>Make things secure"]
        P7["Point 7<br/>Make privacy integral"]
    end
    
    subgraph "Collaboration & Data"
        P8["Point 8<br/>Share, reuse and collaborate"]
        P9["Point 9<br/>Integrate and adapt technology"]
        P10["Point 10<br/>Make better use of data"]
    end
    
    subgraph "Procurement & Governance"
        P11["Point 11<br/>Define your purchasing strategy"]
        P12["Point 12<br/>Meet Digital Spend Controls"]
        P13["Point 13<br/>Define your responsible AI use"]
    end
    
    P1 --> P2
    P3 --> P4
    P4 --> P5
    P6 --> P7
    P8 --> P9
    P9 --> P10
    P11 --> P12
