graph TB
    subgraph "Architecture Family"
        EA["Enterprise Architect<br/>12 commands"]
        SA["Solution Architect<br/>10 commands"]
        DA["Data Architect<br/>4 commands"]
        SecA["Security Architect<br/>5 commands"]
        BA["Business Architect<br/>5 commands"]
        TA["Technical Architect<br/>5 commands"]
        NA["Network Architect<br/>3 commands"]
    end
    
    subgraph "Chief Digital and Data Family"
        CTO["CTO/CDIO<br/>5 commands"]
        CDO["CDO<br/>4 commands"]
        CISO["CISO<br/>5 commands"]
    end
    
    subgraph "Product and Delivery Family"
        PM["Product Manager<br/>5 commands"]
        DM["Delivery Manager<br/>6 commands"]
        BAn["Business Analyst<br/>4 commands"]
        SO["Service Owner<br/>3 commands"]
    end
    
    subgraph "Data Family"
        DGM["Data Governance Manager<br/>4 commands"]
        PA["Performance Analyst<br/>4 commands"]
    end
    
    subgraph "IT Operations Family"
        ITSM["IT Service Manager<br/>3 commands"]
    end
    
    subgraph "Software Development Family"
        DE["DevOps Engineer<br/>3 commands"]
    end
